#!/bin/bash
# test-e2e-versions-lock.sh — Regression test for docker/e2e/.versions.lock.
#
# The lockfile is the audit record of which versions ship in the e2e Docker
# images. It is regenerated by `task e2e:lock` (via
# scripts/e2e-capture-versions.sh) and committed alongside any image change.
#
# This test pins the file-level contract independent of Docker availability:
#
#   1. The lockfile exists and is tracked by git (not gitignored or stale).
#   2. Every required key documented in docs/adr/0001-e2e-docker-images.md
#      is present.
#   3. captured_at is a syntactically valid ISO 8601 UTC timestamp.
#
# Usage:
#   bash scripts/tests/test-e2e-versions-lock.sh

set -uo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
LOCK_REL="docker/e2e/.versions.lock"
LOCK_ABS="$REPO_ROOT/$LOCK_REL"

PASS=0
FAIL=0

note_pass() { echo "PASS  $1"; PASS=$((PASS + 1)); }
note_fail() { echo "FAIL  $1 — $2"; FAIL=$((FAIL + 1)); }

# ---------------------------------------------------------------------------
# 1. File presence + git-tracked
# ---------------------------------------------------------------------------
if [[ -f "$LOCK_ABS" ]]; then
  note_pass "lockfile exists on disk"
else
  note_fail "lockfile exists on disk" "$LOCK_ABS not found"
  echo "Results: $PASS passed, $FAIL failed"
  exit 1
fi

if ( cd "$REPO_ROOT" && git ls-files --error-unmatch "$LOCK_REL" >/dev/null 2>&1 ); then
  note_pass "lockfile is tracked by git"
else
  note_fail "lockfile is tracked by git" "$LOCK_REL is not in the index"
fi

# ---------------------------------------------------------------------------
# 2. Required keys
# ---------------------------------------------------------------------------
REQUIRED_KEYS=(
  "captured_at"
  "base.debian"
  "base.node"
  "base.npm"
  "base.python"
  "base.pipx"
  "base.gh"
  "base.yq"
  "base.jq"
  "base.ollama"
  "claude.cli"
  "gemini.cli"
  "copilot.cli"
  "mempalace.cli"
)

for key in "${REQUIRED_KEYS[@]}"; do
  if grep -qE "^${key}=" "$LOCK_ABS"; then
    note_pass "key present: $key"
  else
    note_fail "key present: $key" "no line starts with '${key}='"
  fi
done

# ---------------------------------------------------------------------------
# 3. captured_at format — ISO 8601 UTC
# ---------------------------------------------------------------------------
captured_at_line="$(grep -E '^captured_at=' "$LOCK_ABS" | head -n1)"
captured_at_value="${captured_at_line#captured_at=}"
if [[ "$captured_at_value" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$ ]]; then
  note_pass "captured_at is ISO 8601 UTC ($captured_at_value)"
else
  note_fail "captured_at is ISO 8601 UTC" "got: $captured_at_value"
fi

echo ""
echo "Results: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]]
