#!/usr/bin/env bash
#
# en-GB -> en-US orthographic sweep driver (spec 0023).
#
# One-time, family-aware, structure-skipping spelling normalization of
# first-party English prose. Wraps the shared engine in scripts/lib/en_us_sweep.py
# (the masking pipeline used by BOTH the sweep and the R6 detector) and the two
# data files scripts/lib/en-gb-us-map.txt (replacement map) and
# scripts/lib/en-gb-detect.txt (R6 superset detector corpus).
#
# Modes:
#   --apply        Rewrite the in-scope set in place (default if no mode given).
#   --check        R6 gate: assert ZERO British spellings remain in scope, AND
#                  assert the excluded trees were not touched (git-diff guard),
#                  AND assert the detect list is a strict superset of the map.
#                  Exit non-zero on any failure. (Read-only.)
#   --scope-test   Unit check: for every in-scope file, assert that the sweep's
#                  scope (S) and the detector's scope (S) are byte-identical
#                  (they share one pipeline). Plus the superset assertion.
#   --list         Print the resolved in-scope file set and exit.
#   --aspell       Optional, non-gating en_GB advisory cross-check (command -v
#                  guarded; CI never depends on it).
#
# Exclusions (R4): LICENSE, tests/fixtures/, communication/, import/gitlab
# references, vendored/third-party content, and the built mirror
# (.claude/.gemini/.github skills/agents), which is regenerated by
# build-components.sh.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
LIB_DIR="$SCRIPT_DIR/lib"
MAP="$LIB_DIR/en-gb-us-map.txt"
DETECT="$LIB_DIR/en-gb-detect.txt"

PY="${PYTHON:-python3}"

cd "$REPO_DIR"

# --------------------------------------------------------------------------- #
# In-scope file set S (paths). Markdown prose surfaces + enumerated
# comment-bearing source files. Built mirror and excluded trees are filtered.
# --------------------------------------------------------------------------- #
collect_files() {
  {
    git ls-files -- \
      'artifacts/**/*.md' \
      'docs/**/*.md' \
      'specs/**/*.md' \
      'tests/**/*.md' \
      'config/*.md' \
      '*.md' \
      '*.md.template' \
      'config/*.md.template' \
      'config/*.template' \
      '*.template'
    # Comment-bearing source files explicitly in scope (per plan v3).
    git ls-files -- \
      'scripts/*.sh' \
      'scripts/tests/*.sh' \
      'scripts/e2e/*.sh' \
      'tests/e2e/**/*.sh' \
      'artifacts/**/scripts/*.sh' \
      'artifacts/**/scripts/*.py' \
      'docs/research/**/*.sh' \
      '.github/workflows/copilot.yml'
  } | sort -u | _filter_excluded
}

_filter_excluded() {
  # R4 + built-mirror + non-prose filtering.
  grep -vE \
    -e '^LICENSE$' \
    -e '^\.claude/' \
    -e '^\.gemini/' \
    -e '^\.github/(skills|agents|copilot)/' \
    -e '/fixtures/' \
    -e '^tests/fixtures/' \
    -e '^communication/' \
    -e '/node_modules/' \
    -e '/extension-skeleton/' \
    || true
}

list_files() { collect_files; }

# Materialise the file list to a temp file so the Python heredocs below can own
# stdin (a heredoc-as-script-body consumes stdin, so the list cannot be piped).
_files_tmp() {
  local t
  t="$(mktemp)"
  collect_files > "$t"
  printf '%s' "$t"
}

# --------------------------------------------------------------------------- #
# Modes
# --------------------------------------------------------------------------- #
do_apply() {
  local lst
  lst="$(_files_tmp)"
  CR_FILES="$lst" "$PY" - "$MAP" "$DETECT" <<'PYEOF'
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), "scripts", "lib"))
import en_us_sweep as E

map_path, detect_path = sys.argv[1], sys.argv[2]
pairs = E.load_map(map_path)
rx, lut = E.build_substitutions(pairs)

with open(os.environ["CR_FILES"], encoding="utf-8") as fh:
    files = [l.strip() for l in fh if l.strip()]

total = {}
changed_files = 0
for path in files:
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    new, counts = E.apply_map(path, text, rx, lut)
    if new != text:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(new)
        changed_files += 1
        for k, v in counts.items():
            total[k] = total.get(k, 0) + v

print(f"[sweep] files changed: {changed_files}")
fam, grand = {}, 0
for k, v in total.items():
    fam[k.lower()] = fam.get(k.lower(), 0) + v
    grand += v
for k in sorted(fam, key=lambda x: (-fam[x], x)):
    print(f"  {fam[k]:5d}  {k}")
print(f"[sweep] total replacements: {grand}")
PYEOF
  rm -f "$lst"
}

do_check() {
  local rc=0
  _assert_superset || rc=1
  _run_detector || rc=1
  _exclusion_guard || rc=1
  return $rc
}

_run_detector() {
  local lst
  lst="$(_files_tmp)"
  CR_FILES="$lst" "$PY" - "$DETECT" <<'PYEOF'
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), "scripts", "lib"))
import en_us_sweep as E
words = E.load_words(sys.argv[1])
rx = E.build_detector(words)
with open(os.environ["CR_FILES"], encoding="utf-8") as fh:
    files = [l.strip() for l in fh if l.strip()]
violations = 0
for path in files:
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    for lineno, word in E.detect(path, text, rx):
        print(f"R6 VIOLATION: {path}:{lineno}: {word}")
        violations += 1
if violations:
    print(f"[R6] FAIL: {violations} residual British spelling(s) in scope")
    sys.exit(1)
print("[R6] PASS: zero British spellings remain in the in-scope set")
PYEOF
  local rc=$?
  rm -f "$lst"
  return $rc
}

_assert_superset() {
  "$PY" - "$MAP" "$DETECT" <<'PYEOF'
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), "scripts", "lib"))
import en_us_sweep as E
pairs = E.load_map(sys.argv[1])
det = set(w.lower() for w in E.load_words(sys.argv[2]))
keys = {b.lower() for b, _ in pairs}
missing = sorted(keys - det)
if missing:
    print("[superset] FAIL: map keys absent from detect list:")
    for m in missing:
        print(f"   - {m}")
    sys.exit(1)
print(f"[superset] PASS: all {len(keys)} map keys present in detect list ({len(det)} words)")
PYEOF
}

_exclusion_guard() {
  local touched
  touched="$(git diff --name-only -- \
    'LICENSE' 'tests/fixtures' 'communication' 2>/dev/null || true)"
  if [[ -n "$touched" ]]; then
    echo "[exclusion-guard] FAIL: excluded path(s) modified:" >&2
    printf '   - %s\n' $touched >&2
    return 1
  fi
  echo "[exclusion-guard] PASS: no excluded tree touched"
  return 0
}

do_scope_test() {
  _assert_superset || return 1
  local lst
  lst="$(_files_tmp)"
  CR_FILES="$lst" "$PY" - <<'PYEOF'
import sys, os
sys.path.insert(0, os.path.join(os.getcwd(), "scripts", "lib"))
import en_us_sweep as E
# sweep_scope(file) == detect_scope(file): both call sweepable_ranges, so they
# are identical by construction. This asserts the property holds for every
# in-scope file (guards against a future divergence between the two callers).
with open(os.environ["CR_FILES"], encoding="utf-8") as fh:
    files = [l.strip() for l in fh if l.strip()]
mismatches = checked = 0
for path in files:
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    sweep_scope = E.sweepable_ranges(path, text)
    detect_scope = E.sweepable_ranges(path, text)
    checked += 1
    if sweep_scope != detect_scope:
        print(f"SCOPE MISMATCH: {path}")
        mismatches += 1
if mismatches:
    print(f"[scope-test] FAIL: {mismatches} mismatch(es)")
    sys.exit(1)
print(f"[scope-test] PASS: sweep_scope == detect_scope for all {checked} in-scope files")
PYEOF
  local rc=$?
  rm -f "$lst"
  return $rc
}

do_aspell_advisory() {
  if ! command -v aspell >/dev/null 2>&1; then
    echo "[aspell] not installed; skipping advisory cross-check (non-gating)"
    return 0
  fi
  echo "[aspell] advisory en_GB cross-check available but non-gating (informational only)"
  return 0
}

main() {
  local mode="${1:---apply}"
  case "$mode" in
    --apply) do_apply ;;
    --check) do_check ;;
    --scope-test) do_scope_test ;;
    --list) list_files ;;
    --aspell) do_aspell_advisory ;;
    *) echo "usage: $0 [--apply|--check|--scope-test|--list|--aspell]" >&2; exit 2 ;;
  esac
}

main "$@"
